import json

cells_content = [
    [
        "# ==============================================================================\n",
        "# CELL 1: Install Dependencies (Added OCR Image Parsers)\n",
        "# ==============================================================================\n",
        "\n",
        "!pip install -q gradio requests pdf2image\n",
        "!apt-get update -y\n",
        "!apt-get install -y poppler-utils tesseract-ocr"
    ],
    [
        "# ================================\n",
        "# CELL 2: 🔧 INSTALL OLLAMA (KAGGLE LOCAL)\n",
        "# ================================\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "import time\n",
        "import requests\n",
        "\n",
        "print(\"🧹 Cleaning old/broken Ollama install...\")\n",
        "!rm -rf /usr/local/lib/ollama\n",
        "!rm -rf /usr/local/bin/ollama\n",
        "\n",
        "print(\"📦 Installing required dependencies...\")\n",
        "!apt-get update -y\n",
        "!apt-get install -y curl zstd ca-certificates\n",
        "\n",
        "print(\"⬇️ Installing Ollama...\")\n",
        "!curl -fsSL https://ollama.com/install.sh | sh\n",
        "\n",
        "print(\"🔍 Verifying installation...\")\n",
        "!ls /usr/local/bin/ollama\n",
        "\n",
        "print(\"🚀 Starting Ollama server...\")\n",
        "env = os.environ.copy()\n",
        "env[\"CUDA_VISIBLE_DEVICES\"] = \"0\"\n",
        "env[\"OLLAMA_NUM_PARALLEL\"] = \"4\"\n",
        "env[\"OLLAMA_MAX_LOADED_MODELS\"] = \"2\"\n",
        "\n",
        "ollama_process = subprocess.Popen(\n",
        "    [\"/usr/local/bin/ollama\", \"serve\"],\n",
        "    env=env,\n",
        "    stdout=subprocess.PIPE,\n",
        "    stderr=subprocess.PIPE\n",
        ")\n",
        "time.sleep(10)\n",
        "\n",
        "def check_ollama():\n",
        "    try:\n",
        "        r = requests.get(\"http://localhost:11434/api/tags\")\n",
        "        return r.status_code == 200\n",
        "    except:\n",
        "        return False\n",
        "\n",
        "if check_ollama():\n",
        "    print(\"✅ Ollama is RUNNING!\")\n",
        "else:\n",
        "    print(\"❌ Ollama failed to start\")\n",
        "\n",
        "print(\"📥 Pulling llama3 model (first time takes time)...\")\n",
        "!ollama pull llama3:8b\n",
        "print(\"✅ Setup Complete!\")"
    ],
    [
        "# ==============================================================================\n",
        "# CELL 3: OCR & TEXT EXTRACTION ENGINE (PRODUCTION READY)\n",
        "# ==============================================================================\n",
        "\n",
        "import io\n",
        "import base64\n",
        "import json\n",
        "from pdf2image import convert_from_path\n",
        "\n",
        "OCR_SPACE_API_KEY = \"K87093604688957\"\n",
        "pdf_cache = {} # Cache files to prevent re-running OCR during UI tweaks\n",
        "\n",
        "def extract_text_from_file(file_path):\n",
        "    if not file_path: return \"\"\n",
        "    file_path_lower = file_path.lower()\n",
        "    \n",
        "    if file_path_lower.endswith(('.png', '.jpg', '.jpeg')):\n",
        "        print(f\"Processing Image '{file_path}' via OCR.space API...\")\n",
        "        with open(file_path, \"rb\") as f:\n",
        "            base64_encoded = base64.b64encode(f.read()).decode('utf-8')\n",
        "        \n",
        "        payload = {\n",
        "            'apikey': OCR_SPACE_API_KEY,\n",
        "            'base64Image': f\"data:image/jpeg;base64,{base64_encoded}\",\n",
        "            'language': 'eng',\n",
        "            'isOverlayRequired': False\n",
        "        }\n",
        "        try:\n",
        "            response = requests.post('https://api.ocr.space/parse/image', data=payload)\n",
        "            result = response.json()\n",
        "            if result.get('IsErroredOnProcessing') == False:\n",
        "                return result['ParsedResults'][0]['ParsedText']\n",
        "            else:\n",
        "                print(f\"OCR Image Error: {result.get('ErrorMessage')}\")\n",
        "                return \"\"\n",
        "        except Exception as e:\n",
        "            print(f\"Image OCR Request failed: {e}\")\n",
        "            return \"\"\n",
        "            \n",
        "    elif file_path_lower.endswith('.pdf'):\n",
        "        print(f\"Converting PDF '{file_path}' to images for OCR...\")\n",
        "        images = convert_from_path(file_path, dpi=100) \n",
        "        full_text = \"\"\n",
        "        \n",
        "        for i, img in enumerate(images):\n",
        "            print(f\"Processing PDF Page {i+1} via OCR...\")\n",
        "            img_byte_arr = io.BytesIO()\n",
        "            img.save(img_byte_arr, format='JPEG', quality=40) \n",
        "            base64_encoded = base64.b64encode(img_byte_arr.getvalue()).decode('utf-8')\n",
        "            \n",
        "            payload = {\n",
        "                'apikey': OCR_SPACE_API_KEY,\n",
        "                'base64Image': f\"data:image/jpeg;base64,{base64_encoded}\",\n",
        "                'language': 'eng',\n",
        "                'isOverlayRequired': False\n",
        "            }\n",
        "            \n",
        "            try:\n",
        "                response = requests.post('https://api.ocr.space/parse/image', data=payload)\n",
        "                result = response.json()\n",
        "                if result.get('IsErroredOnProcessing') == False:\n",
        "                    parsed_text = result['ParsedResults'][0]['ParsedText']\n",
        "                    full_text += parsed_text + \"\\n\\n\"\n",
        "                else:\n",
        "                    print(f\"API Error on Page {i+1}: {result.get('ErrorMessage')}\")\n",
        "            except Exception as e:\n",
        "                print(f\"Request failed for Page {i+1}: {e}\")\n",
        "                \n",
        "            time.sleep(1)\n",
        "        return full_text\n",
        "    else:\n",
        "        # Fallback to direct raw text reading if uploaded as .txt file\n",
        "        try:\n",
        "            with open(file_path, \"r\", encoding=\"utf-8\") as f:\n",
        "                return f.read()\n",
        "        except:\n",
        "            return \"UNSUPPORTED FILE FORMAT\"\n"
    ],
    [
        "# CELL 4: CAR CLAIM EVALUATION ENGINE\n",
        "import gradio as gr\n",
        "\n",
        "OLLAMA_API_URL = \"http://localhost:11434/api/generate\"\n",
        "\n",
        "def call_ollama(prompt, system_prompt):\n",
        "    payload = {\n",
        "        \"model\": \"llama3:8b\",\n",
        "        \"prompt\": prompt,\n",
        "        \"system\": system_prompt,\n",
        "        \"stream\": False,\n",
        "        \"format\": \"json\"\n",
        "    }\n",
        "    try:\n",
        "        response = requests.post(OLLAMA_API_URL, json=payload, timeout=300)\n",
        "        response.raise_for_status()\n",
        "        return response.json().get('response', '{}')\n",
        "    except Exception as e:\n",
        "        print(f\"Ollama inference error: {e}\")\n",
        "        return \"{}\"\n",
        "\n",
        "def car_claim_evaluator(policy_text, bill_text):\n",
        "    print(\"🚙 Analyzing Scanned Bill against Scanned Policy Rules...\")\n",
        "    sys_prompt = \"\"\"You are an Automated Car Insurance Claim Evaluation Engine.\n",
        "\n",
        "Your task is to analyze:\n",
        "1. Insurance Policy Document\n",
        "2. Damage Bill / Repair Invoice\n",
        "\n",
        "You MUST automatically determine:\n",
        "- What is covered\n",
        "- What is NOT covered\n",
        "- Final payable amount by the insurance company\n",
        "\n",
        "You DO NOT ask the user questions.\n",
        "You DO NOT wait for user input.\n",
        "You COMPLETE the full evaluation in one go.\n",
        "\n",
        "================================\n",
        "PHASE 1: POLICY UNDERSTANDING\n",
        "================================\n",
        "Extract and structure:\n",
        "{ \"coverage_items\": [...], \"exclusions\": [...], \"deductibles\": [...], \"limits\": {...}, \"special_conditions\": [...] }\n",
        "\n",
        "================================\n",
        "PHASE 2: BILL PARSING\n",
        "================================\n",
        "Extract all bill items:\n",
        "[ { \"item\": \"...\", \"cost\": number, \"category\": \"repair/part/labor/service\" } ]\n",
        "\n",
        "================================\n",
        "PHASE 3: CLAIM EVALUATION\n",
        "================================\n",
        "For EACH bill item:\n",
        "- Check if covered under policy\n",
        "- Apply exclusions\n",
        "- Apply limits/deductibles\n",
        "Return:\n",
        "[ { \"item\": \"...\", \"cost\": number, \"covered\": true/false, \"payable_amount\": number, \"reason\": \"short explanation\" } ]\n",
        "\n",
        "================================\n",
        "PHASE 4: FINAL CALCULATION\n",
        "================================\n",
        "- Sum all payable amounts\n",
        "- Apply deductibles if any\n",
        "- Ensure limits are respected\n",
        "\n",
        "================================\n",
        "FINAL OUTPUT (VERY IMPORTANT)\n",
        "================================\n",
        "Return ONLY this JSON:\n",
        "{\n",
        "  \"total_bill_amount\": number,\n",
        "  \"total_covered_amount\": number,\n",
        "  \"total_not_covered_amount\": number,\n",
        "  \"final_payable_by_insurer\": number,\n",
        "  \"breakdown\": [],\n",
        "  \"summary\": { \"covered_items\": [], \"not_covered_items\": [], \"key_reasons\": [] },\n",
        "  \"human_readable_summary\": \"Insurance will pay: ₹XXXXX \\nYou must pay: ₹XXXXX \\nMain uncovered items: ...\"\n",
        "}\n",
        "\n",
        "================================\n",
        "RULES\n",
        "================================\n",
        "- Be precise and simple\n",
        "- No unnecessary text\n",
        "- No explanations outside JSON\n",
        "- No assumptions beyond policy\n",
        "- If unclear, mark as NOT covered with reason\n",
        "- No external APIs\n",
        "- No audio or ElevenLabs\n",
        "\"\"\"\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "INPUT STRUCTURE\n",
        "\n",
        "POLICY:\n",
        "{policy_text}\n",
        "\n",
        "BILL:\n",
        "{bill_text}\n",
        "\"\"\"\n",
        "    \n",
        "    raw_json = call_ollama(prompt, sys_prompt)\n",
        "    try:\n",
        "        data = json.loads(raw_json)\n",
        "        simple_msg = data.pop(\"human_readable_summary\", \"No summary returned.\")\n",
        "        return data, simple_msg\n",
        "    except Exception as e:\n",
        "        return {\"error\": \"Failed to parse JSON. Try Again.\", \"raw\": raw_json}, str(e)"
    ],
    [
        "# CELL 5: UI AND PRODUCTION LAUNCHER (FILE UPLOAD SUPPORT)\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "def process_pipeline(policy_file, bill_file):\n",
        "    if not policy_file or not bill_file:\n",
        "        return {\"error\": \"Upload both the Policy and the Bill files!\"}, \"⚠️ Missing Uploads\"\n",
        "        \n",
        "    policy_path = policy_file.name if hasattr(policy_file, 'name') else str(policy_file)\n",
        "    bill_path = bill_file.name if hasattr(bill_file, 'name') else str(bill_file)\n",
        "    \n",
        "    # Memory Caching to prevent re-extracting if user just clicks submit again\n",
        "    if policy_path not in pdf_cache:\n",
        "        print(\"Extracting Policy Data...\")\n",
        "        pdf_cache[policy_path] = extract_text_from_file(policy_path)\n",
        "    \n",
        "    if bill_path not in pdf_cache:\n",
        "        print(\"Extracting Invoice Data...\")\n",
        "        pdf_cache[bill_path] = extract_text_from_file(bill_path)\n",
        "        \n",
        "    policy_text = pdf_cache[policy_path]\n",
        "    bill_text = pdf_cache[bill_path]\n",
        "    \n",
        "    if not policy_text or not bill_text:\n",
        "        return {\"error\": \"OCR failed to extract text from one of the files.\"}, \"⚠️ Extraction Failed\"\n",
        "        \n",
        "    return car_claim_evaluator(policy_text, bill_text)\n",
        "\n",
        "interface = gr.Interface(\n",
        "    fn=process_pipeline,\n",
        "    inputs=[\n",
        "        gr.File(label=\"📄 Upload Car Insurance Policy (PDF/Image/TXT)\"),\n",
        "        gr.File(label=\"🧾 Upload Damage Repair Bill/Invoice (PDF/Image/TXT)\")\n",
        "    ],\n",
        "    outputs=[\n",
        "        gr.JSON(label=\"🖥️ Exact Calculation Breakdown (JSON)\"),\n",
        "        gr.Markdown(label=\"⚡ Simple Human Readable Summary\")\n",
        "    ],\n",
        "    title=\"ClaimGuard AI 🚘 - Production Claim Evaluator\",\n",
        "    description=\"Upload real-world Photos or PDFs of a Repair Bill and the Policy document. The system uses built-in Multi-format OCR to digitize them and auto-calculates exactly what is owed.\"\n",
        ")\n",
        "\n",
        "try:\n",
        "    _ = interface.launch(share=True, inline=False, quiet=True)\n",
        "    print(\"✅ Production Claim Evaluator Deployed! Upload your files via the public *.gradio.live link.\")\n",
        "except Exception as e:\n",
        "    print(f\"Gradio Launch Error: {e}\")"
    ]
]

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚘 ClaimGuard AI V10 (Production File Processing Engine)\n",
                "Full-scale architecture mapping local OCR (PDFs & JPEGs) directly into the master Car Evaluator logic."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

for i, code_lines in enumerate(cells_content):
    cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": code_lines
    }
    notebook["cells"].append(cell)

with open(r"c:\Users\raj17\Desktop\ClaimGuard AI\ClaimGuard_AI_Kaggle_v10.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("Notebook v10 generated successfully!")
