import json

cells_content = [
    [
        "# ==============================================================================\n",
        "# CELL 1: Install Dependencies (Added gTTS for Bengali audio fallback)\n",
        "# ==============================================================================\n",
        "\n",
        "# Install Python packages (REMOVED nest-asyncio, Added gTTS)\n",
        "!pip install -q pdf2image gradio faiss-cpu sentence-transformers requests reportlab gTTS\n",
        "\n",
        "# Install system dependencies\n",
        "!apt-get update -y\n",
        "!apt-get install -y poppler-utils tesseract-ocr"
    ],
    [
        "# ================================\n",
        "# CELL 2: 🔧 FIX OLLAMA INSTALL (KAGGLE)\n",
        "# ================================\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "import time\n",
        "import requests\n",
        "\n",
        "print(\"🧹 Cleaning old/broken Ollama install...\")\n",
        "!rm -rf /usr/local/lib/ollama\n",
        "!rm -rf /usr/local/bin/ollama\n",
        "\n",
        "print(\"📦 Installing required dependencies...\")\n",
        "!apt-get update -y\n",
        "!apt-get install -y curl zstd ca-certificates\n",
        "\n",
        "print(\"⬇️ Installing Ollama...\")\n",
        "!curl -fsSL https://ollama.com/install.sh | sh\n",
        "\n",
        "print(\"🔍 Verifying installation...\")\n",
        "!ls /usr/local/bin/ollama\n",
        "\n",
        "# ================================\n",
        "# 🚀 START OLLAMA SERVER\n",
        "# ================================\n",
        "\n",
        "print(\"🚀 Starting Ollama server...\")\n",
        "\n",
        "env = os.environ.copy()\n",
        "env[\"CUDA_VISIBLE_DEVICES\"] = \"0\"   # Kaggle = 1 GPU\n",
        "env[\"OLLAMA_NUM_PARALLEL\"] = \"4\"\n",
        "env[\"OLLAMA_MAX_LOADED_MODELS\"] = \"2\"\n",
        "\n",
        "ollama_process = subprocess.Popen(\n",
        "    [\"/usr/local/bin/ollama\", \"serve\"],\n",
        "    env=env,\n",
        "    stdout=subprocess.PIPE,\n",
        "    stderr=subprocess.PIPE\n",
        ")\n",
        "\n",
        "time.sleep(10)  # give time to start\n",
        "\n",
        "# ================================\n",
        "# ✅ CHECK IF RUNNING\n",
        "# ================================\n",
        "\n",
        "def check_ollama():\n",
        "    try:\n",
        "        r = requests.get(\"http://localhost:11434/api/tags\")\n",
        "        return r.status_code == 200\n",
        "    except:\n",
        "        return False\n",
        "\n",
        "if check_ollama():\n",
        "    print(\"✅ Ollama is RUNNING!\")\n",
        "else:\n",
        "    print(\"❌ Ollama failed to start\")\n",
        "    print(\"Logs:\")\n",
        "    print(ollama_process.stderr.read().decode()[:500])\n",
        "\n",
        "# ================================\n",
        "# 📥 PULL MODEL\n",
        "# ================================\n",
        "\n",
        "print(\"📥 Pulling llama3 model (first time takes time)...\")\n",
        "!ollama pull llama3:8b\n",
        "\n",
        "print(\"✅ Setup Complete!\")"
    ],
    [
        "# ==============================================================================\n",
        "# CELL 3: Imports & Configuration\n",
        "# ==============================================================================\n",
        "\n",
        "import os\n",
        "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
        "\n",
        "import io\n",
        "import re\n",
        "import json\n",
        "import time\n",
        "import base64\n",
        "import requests\n",
        "import faiss\n",
        "import numpy as np\n",
        "import torch\n",
        "from pdf2image import convert_from_path\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from gtts import gTTS\n",
        "import gradio as gr\n",
        "\n",
        "# API Keys & Configurations\n",
        "OCR_SPACE_API_KEY = \"K87093604688957\"\n",
        "OLLAMA_API_URL = \"http://localhost:11434/api/generate\"\n",
        "ELEVENLABS_API_KEY = \"sk_f8f0b0203444a36ae7cfa53baff0ae16b8042086b53d85c8\"\n",
        "EMBEDDING_MODEL_NAME = 'all-MiniLM-L6-v2'\n",
        "\n",
        "print(\"Loading Embedding Model (CPU safe mode)...\")\n",
        "embedder = SentenceTransformer(EMBEDDING_MODEL_NAME, device=\"cpu\")\n",
        "print(\"✅ Embedding model loaded successfully on CPU\")\n",
        "\n",
        "# Global stores\n",
        "vector_db = None\n",
        "clause_store = []\n",
        "pdf_cache = {}"
    ],
    [
        "# CELL 4: 1. OCR MODULE (OCR.space Integration)\n",
        "def extract_text_from_pdf(pdf_path):\n",
        "    print(\"Converting PDF to images for OCR...\")\n",
        "    images = convert_from_path(pdf_path, dpi=100) \n",
        "    full_text = \"\"\n",
        "    \n",
        "    for i, img in enumerate(images):\n",
        "        print(f\"Processing Page {i+1} via OCR.space API...\")\n",
        "        img_byte_arr = io.BytesIO()\n",
        "        img.save(img_byte_arr, format='JPEG', quality=40) \n",
        "        base64_encoded = base64.b64encode(img_byte_arr.getvalue()).decode('utf-8')\n",
        "        \n",
        "        payload = {\n",
        "            'apikey': OCR_SPACE_API_KEY,\n",
        "            'base64Image': f\"data:image/jpeg;base64,{base64_encoded}\",\n",
        "            'language': 'eng',\n",
        "            'isOverlayRequired': False\n",
        "        }\n",
        "        \n",
        "        try:\n",
        "            response = requests.post('https://api.ocr.space/parse/image', data=payload)\n",
        "            result = response.json()\n",
        "            if result.get('IsErroredOnProcessing') == False:\n",
        "                parsed_text = result['ParsedResults'][0]['ParsedText']\n",
        "                full_text += parsed_text + \"\\n\\n\"\n",
        "            else:\n",
        "                print(f\"API Error on Page {i+1}: {result.get('ErrorMessage')}\")\n",
        "        except Exception as e:\n",
        "            print(f\"Request failed for Page {i+1}: {e}\")\n",
        "            \n",
        "        time.sleep(1) \n",
        "        \n",
        "    return full_text"
    ],
    [
        "# CELL 5: 2. NLP TEXT PROCESSING MODULE\n",
        "def process_text(raw_text):\n",
        "    print(\"Cleaning and chunking text...\")\n",
        "    cleaned = re.sub(r'\\s+', ' ', raw_text).strip()\n",
        "    words = cleaned.split()\n",
        "    \n",
        "    chunk_size = 300\n",
        "    overlap = 50\n",
        "    chunks = [\" \".join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size - overlap)]\n",
        "\n",
        "    categories = {\n",
        "        \"waiting_period\": [\"waiting\", \"days from inception\", \"delay\"],\n",
        "        \"exclusion\": [\"excluded\", \"not covered\", \"exclusion\", \"except\"],\n",
        "        \"co_payment\": [\"co-pay\", \"copayment\", \"co payment\", \"%\"],\n",
        "        \"room_rent\": [\"room rent\", \"bed charges\", \"icu\"],\n",
        "        \"sub_limit\": [\"sub-limit\", \"capped at\", \"maximum limit\"],\n",
        "        \"network_rule\": [\"network\", \"empanelled\", \"hospital\"]\n",
        "    }\n",
        "    \n",
        "    structured_clauses = []\n",
        "    \n",
        "    for chunk in chunks:\n",
        "        cls_tags = []\n",
        "        lower_chunk = chunk.lower()\n",
        "        for cat, keywords in categories.items():\n",
        "            if any(k in lower_chunk for k in keywords):\n",
        "                cls_tags.append(cat)\n",
        "                \n",
        "        structured_clauses.append({\n",
        "            \"text\": chunk,\n",
        "            \"categories\": cls_tags if cls_tags else [\"general\"]\n",
        "        })\n",
        "        \n",
        "    print(f\"Extracted {len(structured_clauses)} structural clause chunks.\")\n",
        "    return structured_clauses"
    ],
    [
        "# CELL 6: 3. EMBEDDING + VECTOR DB (FAISS)\n",
        "def build_vector_db(structured_clauses):\n",
        "    global vector_db, clause_store\n",
        "    clause_store = structured_clauses\n",
        "    texts = [c['text'] for c in structured_clauses]\n",
        "    \n",
        "    print(\"Generating FAISS Embeddings...\")\n",
        "    embeddings = embedder.encode(texts).astype('float32')\n",
        "    \n",
        "    dimension = embeddings.shape[1]\n",
        "    vector_db = faiss.IndexFlatL2(dimension)\n",
        "    vector_db.add(embeddings)\n",
        "    print(f\"Vector DB initialized with {vector_db.ntotal} clause embeddings.\")\n",
        "\n",
        "def get_relevant_clauses(query, top_k=5):\n",
        "    if not vector_db: return []\n",
        "    query_vector = embedder.encode([query]).astype('float32')\n",
        "    distances, indices = vector_db.search(query_vector, top_k)\n",
        "    return [clause_store[idx] for idx in indices[0] if idx < len(clause_store)]"
    ],
    [
        "# CELL 7: 4. SCENARIO PARSER (Ollama JSON Parsing)\n",
        "def call_ollama(prompt, system_prompt, json_format=True):\n",
        "    payload = {\n",
        "        \"model\": \"llama3:8b\", # Matched model tag with CELL 2\n",
        "        \"prompt\": prompt,\n",
        "        \"system\": system_prompt,\n",
        "        \"stream\": False\n",
        "    }\n",
        "    if json_format:\n",
        "        payload[\"format\"] = \"json\"\n",
        "        \n",
        "    try:\n",
        "        response = requests.post(OLLAMA_API_URL, json=payload, timeout=120)\n",
        "        response.raise_for_status()\n",
        "        return response.json().get('response', '{}' if json_format else '')\n",
        "    except Exception as e:\n",
        "        print(f\"Ollama inference error: {e}\")\n",
        "        return \"{}\" if json_format else \"\"\n",
        "\n",
        "def parse_scenario(user_query):\n",
        "    print(\"Parsing scenario intent via Llama 3...\")\n",
        "    sys_prompt = \"Convert user healthcare scenario to structured JSON with exactly keys: treatment, hospital, urgency, input_raw, estimated_cost.\"\n",
        "    response = call_ollama(user_query, system_prompt=sys_prompt)\n",
        "    \n",
        "    try:\n",
        "        return json.loads(response)\n",
        "    except:\n",
        "        return {\"input_raw\": user_query, \"hospital\": \"Unknown\", \"treatment\": \"Unknown\"}"
    ],
    [
        "# CELL 8: ELITE AI DECISION ENGINE\n",
        "def elite_decision_engine(scenario_json, context_clauses):\n",
        "    print(\"🧠 Engaging Elite AI Risk Analyst Engine...\")\n",
        "    context_text = \"\\n\".join([f\"- {c['text']}\" for c in context_clauses])\n",
        "    \n",
        "    sys_prompt = \"\"\"You are an Elite AI Risk Analyst, Financial Engineer, and Insurance Claim Auditor.\n",
        "Your task is to act as an INTELLIGENT DECISION ENGINE. \n",
        "DO NOT just answer the query. You MUST:\n",
        "1. Infer missing data\n",
        "2. Perform calculations\n",
        "3. Show step-by-step reasoning\n",
        "4. Justify every output\n",
        "5. Reveal hidden risks\n",
        "6. Add insights that are NOT explicitly asked\n",
        "\n",
        "For missing data, intelligently estimate (e.g., average treatment costs, ICU stays, medications). State \"Assumption Made:\" and \"Reason:\".\n",
        "Act like an insurance company trying to reject the claim, exposing traps and loopholes.\n",
        "Predict future policy states and provide optimization strategies for the user.\n",
        "\n",
        "OUTPUT STRICTLY IN THIS EXACT VALID JSON FORMAT (No markdown, no preamble):\n",
        "{\n",
        "  \"assumptions\": [\"Assumption Made: [..] Reason: [..]\"],\n",
        "  \"calculation_steps\": [\n",
        "    \"Step 1: Estimated total bill...\",\n",
        "    \"Step 2: Applied constraints...\",\n",
        "    \"Step 3: Deductions...\",\n",
        "    \"Step 4: Final payout...\"\n",
        "  ],\n",
        "  \"final_payout\": \"string\",\n",
        "  \"deductions\": [\"List of specific deductions with clause references\"],\n",
        "  \"risks\": [\"Top 5 rejection risks / technical loopholes\"],\n",
        "  \"hidden_insights\": [\"Insights NOT explicitly asked\"],\n",
        "  \"claim_probability\": \"string\",\n",
        "  \"risk_score\": \"string\",\n",
        "  \"coverage_efficiency\": \"string\",\n",
        "  \"future_prediction\": \"string\",\n",
        "  \"optimization_suggestions\": [\"Actionable alternative strategies\"]\n",
        "}\"\"\"\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "INPUT RECEIVED:\n",
        "1. User Scenario & Partial Financials:\n",
        "{json.dumps(scenario_json, indent=2)}\n",
        "\n",
        "2. Policy Clauses (FAISS Retrieved Context):\n",
        "{context_text}\n",
        "\n",
        "Execute the Elite Decision Engine protocol now. Return ONLY valid JSON.\n",
        "\"\"\"\n",
        "    \n",
        "    try:\n",
        "        resp = call_ollama(prompt, system_prompt=sys_prompt, json_format=True)\n",
        "        return json.loads(resp)\n",
        "    except Exception as e:\n",
        "        print(f\"⚠️ Engine Execution Failed: {e}\")\n",
        "        return {}\n",
        "\n",
        "def format_elite_report(audit_json):\n",
        "    try:\n",
        "        report = f\"\"\"\n",
        "# 🧠 ELITE AI RISK ANALYST REPORT\n",
        "\n",
        "### 📊 DECISION METRICS\n",
        "- **Claim Approval Probability:** `{audit_json.get('claim_probability', 'N/A')}`\n",
        "- **Financial Risk Score:** `{audit_json.get('risk_score', 'N/A')}`\n",
        "- **Coverage Efficiency:** `{audit_json.get('coverage_efficiency', 'N/A')}`\n",
        "\n",
        "### 🧩 INFERRED DATA & ASSUMPTIONS\n",
        "{chr(10).join([f\"- {a}\" for a in audit_json.get('assumptions', [])])}\n",
        "\n",
        "### 💰 FINANCIAL CALCULATIONS & PAYOUT\n",
        "**Final Estimated Payout:** **{audit_json.get('final_payout', '₹0')}**\n",
        "\n",
        "**Step-by-Step Reasoning:**\n",
        "{chr(10).join([f\"- {step}\" for step in audit_json.get('calculation_steps', [])])}\n",
        "\n",
        "**Applied Deductions:**\n",
        "{chr(10).join([f\"- {d}\" for d in audit_json.get('deductions', [])])}\n",
        "\n",
        "### ⚠️ ADVERSARIAL RISK ANALYSIS & LOOPHOLES\n",
        "{chr(10).join([f\"🚨 **RISK:** {r}\" for r in audit_json.get('risks', [])])}\n",
        "\n",
        "### 🔍 HIDDEN INSIGHTS\n",
        "{chr(10).join([f\"👀 {h}\" for h in audit_json.get('hidden_insights', [])])}\n",
        "\n",
        "### 🧬 FUTURE PREDICTION\n",
        "{audit_json.get('future_prediction', 'N/A')}\n",
        "\n",
        "### 🔄 STRATEGIC OPTIMIZATION\n",
        "{chr(10).join([f\"💡 {opt}\" for opt in audit_json.get('optimization_suggestions', [])])}\n",
        "\"\"\"\n",
        "        return report\n",
        "    except Exception as e:\n",
        "        return f\"Formatting error: {str(e)}\""
    ],
    [
        "# CELL 9: 🌍 TRANSLATION & TEXT-TO-SPEECH HYBRID ENGINE\n",
        "def generate_simple_translations(english_report):\n",
        "    print(\"🌍 Translating to simple Hindi & Bengali via Llama 3...\")\n",
        "    base_sys_prompt = \"You are a helpful assistant translating healthcare insurance reports into very simple, everyday language for older generations. Avoid complex jargon. Clearly state the final payout, deductions, and biggest risks.\"\n",
        "    \n",
        "    hindi_prompt = f\"Summarize and translate this report into VERY SIMPLE Hindi:\\n\\n{english_report}\\n\\nOutput STRICTLY the simple Hindi text.\"\n",
        "    bengali_prompt = f\"Summarize and translate this report into VERY SIMPLE Bengali:\\n\\n{english_report}\\n\\nOutput STRICTLY the simple Bengali text.\"\n",
        "    \n",
        "    hindi_translation = call_ollama(hindi_prompt, system_prompt=base_sys_prompt, json_format=False).strip()\n",
        "    bengali_translation = call_ollama(bengali_prompt, system_prompt=base_sys_prompt, json_format=False).strip()\n",
        "    \n",
        "    if not hindi_translation: hindi_translation = \"पॉलिसी चेक करें।\"\n",
        "    if not bengali_translation: bengali_translation = \"পলিসি চেক করুন।\"\n",
        "        \n",
        "    # Secure encoding fixes Kaggle string corruption\n",
        "    hindi_translation = hindi_translation.encode(\"utf-8\").decode(\"utf-8\")\n",
        "    bengali_translation = bengali_translation.encode(\"utf-8\").decode(\"utf-8\")\n",
        "    \n",
        "    return hindi_translation, bengali_translation\n",
        "\n",
        "def generate_hindi_elevenlabs(hindi_text, output_path=\"hindi_report.mp3\"):\n",
        "    print(\"🔊 Generating Hindi speech via ElevenLabs API...\")\n",
        "    headers = {\"xi-api-key\": ELEVENLABS_API_KEY}\n",
        "    try:\n",
        "        voices_res = requests.get(\"https://api.elevenlabs.io/v1/voices\", headers=headers)\n",
        "        voices_res.raise_for_status()\n",
        "        voice_id = voices_res.json()[\"voices\"][0][\"voice_id\"]\n",
        "    except Exception as e:\n",
        "        voice_id = \"21m00Tcm4TlvDq8ikWAM\"\n",
        "        \n",
        "    url = f\"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}\"\n",
        "    headers_post = {\n",
        "        \"Accept\": \"audio/mpeg\",\n",
        "        \"Content-Type\": \"application/json\",\n",
        "        \"xi-api-key\": ELEVENLABS_API_KEY\n",
        "    }\n",
        "    data = {\n",
        "        \"text\": hindi_text[:2000],\n",
        "        \"model_id\": \"eleven_multilingual_v2\",\n",
        "    }\n",
        "    try:\n",
        "        response = requests.post(url, json=data, headers=headers_post)\n",
        "        if response.status_code == 200:\n",
        "            with open(output_path, \"wb\") as f:\n",
        "                f.write(response.content)\n",
        "            return os.path.abspath(output_path) # Absolute path guarantees Gradio finds it\n",
        "        else:\n",
        "            return None\n",
        "    except Exception as e:\n",
        "        print(\"ElevenLabs failed:\", e)\n",
        "        return None\n",
        "\n",
        "def generate_bengali_gtts(bengali_text, output_path=\"bengali_report.mp3\"):\n",
        "    print(\"🔊 Generating Bengali speech via Google TTS (Native Support)...\")\n",
        "    try:\n",
        "        tts = gTTS(bengali_text, lang='bn')\n",
        "        tts.save(output_path)\n",
        "        return os.path.abspath(output_path)\n",
        "    except Exception as e:\n",
        "        print(\"gTTS failed:\", e)\n",
        "        return None"
    ],
    [
        "# CELL 10: FULL PIPELINE INTEGRATION\n",
        "def run_claim_analysis(pdf_file, user_query):\n",
        "    pdf_path = pdf_file.name if hasattr(pdf_file, 'name') else str(pdf_file)\n",
        "    \n",
        "    if pdf_path not in pdf_cache:\n",
        "        raw_text = extract_text_from_pdf(pdf_path)\n",
        "        clauses = process_text(raw_text)\n",
        "        build_vector_db(clauses)\n",
        "        pdf_cache[pdf_path] = True\n",
        "    else:\n",
        "        print(\"=> Using cached Embeddings for this PDF\")\n",
        "\n",
        "    scenario = parse_scenario(user_query)\n",
        "    context = get_relevant_clauses(user_query, top_k=5)\n",
        "    audit = elite_decision_engine(scenario, context)\n",
        "    \n",
        "    report = format_elite_report(audit)\n",
        "    \n",
        "    hindi_text, bengali_text = generate_simple_translations(report)\n",
        "    hindi_audio = generate_hindi_elevenlabs(hindi_text)\n",
        "    bengali_audio = generate_bengali_gtts(bengali_text)\n",
        "    \n",
        "    return report, hindi_text, bengali_text, hindi_audio, bengali_audio"
    ],
    [
        "# CELL 11: AUTOMATED TEST CASE & UI\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "def create_dummy_pdf(filename=\"sample_policy.pdf\"):\n",
        "    print(\"Generating simulated insurance policy PDF...\")\n",
        "    try:\n",
        "        from reportlab.pdfgen import canvas\n",
        "        c = canvas.Canvas(filename)\n",
        "        c.drawString(100, 750, \"ClaimGuard Sample Health Insurance Policy\")\n",
        "        c.drawString(100, 730, \"1. This policy covers all emergency treatments and accident surgeries.\")\n",
        "        c.drawString(100, 710, \"2. A 10% co-payment (co-pay) is mandatory for all surgical claims.\")\n",
        "        c.drawString(100, 690, \"3. Sub-limit: Room rent is capped at ₹5,000 per day.\")\n",
        "        c.drawString(100, 670, \"4. Waiting period: 30 days initial waiting period from inception.\")\n",
        "        c.drawString(100, 650, \"5. Exclusions: Cosmetic surgery is strictly excluded.\")\n",
        "        c.drawString(100, 630, \"6. Empanelled network hospital Apollo is fully covered.\")\n",
        "        c.save()\n",
        "        print(\"✅ Sample PDF created successfully\")\n",
        "    except Exception as e:\n",
        "        print(\"Failed to build sample PDF:\", e)\n",
        "\n",
        "create_dummy_pdf()\n",
        "print(\"\\n\" + \"=\"*50)\n",
        "print(\"🧪 RUNNING AUTOMATED TEST CASE\")\n",
        "print(\"=\"*50)\n",
        "test_outputs = run_claim_analysis(\"sample_policy.pdf\", \"Accident surgery tomorrow costing 50000 at Apollo\")\n",
        "print(\"Test complete. Outputs attached.\\n\")\n",
        "\n",
        "def gradio_wrapper(pdf, query):\n",
        "    if not pdf or not query: \n",
        "        return \"⚠️ Please upload a PDF and specify a scenario.\", \"\", \"\", None, None\n",
        "    try:\n",
        "        return run_claim_analysis(pdf, query)\n",
        "    except Exception as e:\n",
        "        return f\"Pipeline Error: {str(e)}\", \"\", \"\", None, None\n",
        "\n",
        "interface = gr.Interface(\n",
        "    fn=gradio_wrapper,\n",
        "    inputs=[\n",
        "        gr.File(label=\"📄 Upload Insurance Policy (PDF)\"),\n",
        "        gr.Textbox(label=\"🏥 Enter Medical Claim Scenario\", placeholder=\"e.g., Accident surgery tomorrow costing 50#...\")\n",
        "    ],\n",
        "    outputs=[\n",
        "        gr.Markdown(label=\"🛡️ Elite Risk Analyst Report (English)\"),\n",
        "        gr.Markdown(label=\"🇮🇳 आसान हिंदी अनुवाद (Simple Hindi Texts)\"),\n",
        "        gr.Markdown(label=\"🇧🇩 সহজ বাংলা অনুবাদ (Simple Bengali Texts)\"),\n",
        "        gr.Audio(label=\"▶️ Play Hindi Audio (Using ElevenLabs API)\"),\n",
        "        gr.Audio(label=\"▶️ Play Bengali Audio (Using Google Free TTS)\")\n",
        "    ],\n",
        "    title=\"ClaimGuard AI 🤖 - Intelligent Decision Engine\",\n",
        "    description=\"Upload a policy document and describe a claim scenario to predict claim approval, run adversarial risk analysis, and uncover hidden pitfalls.\"\n",
        ")\n",
        "\n",
        "try:\n",
        "    _ = interface.launch(share=True, inline=False, quiet=True)\n",
        "    print(\"✅ Web UI Deployed! Use the public *.gradio.live link above.\")\n",
        "except Exception as e:\n",
        "    print(f\"Gradio Launch Error: {e}\")"
    ]
]

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 ClaimGuard AI V7 (Ultra Voice Fix: ElevenLabs + gTTS)\n",
                "Fixes ElevenLabs hallucinating Bengali by delegating strictly Hindi to ElevenLabs, and Bengali to Google TTS natively."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

for i, code_lines in enumerate(cells_content):
    cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": code_lines
    }
    notebook["cells"].append(cell)

with open(r"c:\Users\raj17\Desktop\ClaimGuard AI\ClaimGuard_AI_Kaggle_v7.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("Notebook v7 generated successfully!")
