import json

cells_content = [
    [
        "# ==============================================================================\n",
        "# CELL 1: Install Dependencies (Lightweight Engine)\n",
        "# ==============================================================================\n",
        "\n",
        "!pip install -q gradio requests"
    ],
    [
        "# ================================\n",
        "# CELL 2: 🔧 INSTALL OLLAMA (KAGGLE LOCAL)\n",
        "# ================================\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "import time\n",
        "import requests\n",
        "\n",
        "print(\"🧹 Cleaning old/broken Ollama install...\")\n",
        "!rm -rf /usr/local/lib/ollama\n",
        "!rm -rf /usr/local/bin/ollama\n",
        "\n",
        "print(\"📦 Installing required dependencies...\")\n",
        "!apt-get update -y\n",
        "!apt-get install -y curl zstd ca-certificates\n",
        "\n",
        "print(\"⬇️ Installing Ollama...\")\n",
        "!curl -fsSL https://ollama.com/install.sh | sh\n",
        "\n",
        "print(\"🔍 Verifying installation...\")\n",
        "!ls /usr/local/bin/ollama\n",
        "\n",
        "print(\"🚀 Starting Ollama server...\")\n",
        "env = os.environ.copy()\n",
        "env[\"CUDA_VISIBLE_DEVICES\"] = \"0\"\n",
        "env[\"OLLAMA_NUM_PARALLEL\"] = \"4\"\n",
        "env[\"OLLAMA_MAX_LOADED_MODELS\"] = \"2\"\n",
        "\n",
        "ollama_process = subprocess.Popen(\n",
        "    [\"/usr/local/bin/ollama\", \"serve\"],\n",
        "    env=env,\n",
        "    stdout=subprocess.PIPE,\n",
        "    stderr=subprocess.PIPE\n",
        ")\n",
        "time.sleep(10)\n",
        "\n",
        "def check_ollama():\n",
        "    try:\n",
        "        r = requests.get(\"http://localhost:11434/api/tags\")\n",
        "        return r.status_code == 200\n",
        "    except:\n",
        "        return False\n",
        "\n",
        "if check_ollama():\n",
        "    print(\"✅ Ollama is RUNNING!\")\n",
        "else:\n",
        "    print(\"❌ Ollama failed to start\")\n",
        "\n",
        "print(\"📥 Pulling llama3 model (first time takes time)...\")\n",
        "!ollama pull llama3:8b\n",
        "print(\"✅ Setup Complete!\")"
    ],
    [
        "# ==============================================================================\n",
        "# CELL 3: CAR CLAIM EVALUATION ENGINE\n",
        "# ==============================================================================\n",
        "\n",
        "import json\n",
        "import gradio as gr\n",
        "\n",
        "OLLAMA_API_URL = \"http://localhost:11434/api/generate\"\n",
        "\n",
        "def call_ollama(prompt, system_prompt):\n",
        "    payload = {\n",
        "        \"model\": \"llama3:8b\",\n",
        "        \"prompt\": prompt,\n",
        "        \"system\": system_prompt,\n",
        "        \"stream\": False,\n",
        "        \"format\": \"json\"\n",
        "    }\n",
        "    try:\n",
        "        response = requests.post(OLLAMA_API_URL, json=payload, timeout=300)\n",
        "        response.raise_for_status()\n",
        "        return response.json().get('response', '{}')\n",
        "    except Exception as e:\n",
        "        print(f\"Ollama inference error: {e}\")\n",
        "        return \"{}\"\n",
        "\n",
        "def car_claim_evaluator(policy_text, bill_text):\n",
        "    print(\"🚙 Analyzing Bill against Policy Rules...\")\n",
        "    sys_prompt = \"\"\"You are an Automated Car Insurance Claim Evaluation Engine.\n",
        "\n",
        "Your task is to analyze:\n",
        "1. Insurance Policy Document\n",
        "2. Damage Bill / Repair Invoice\n",
        "\n",
        "You MUST automatically determine:\n",
        "- What is covered\n",
        "- What is NOT covered\n",
        "- Final payable amount by the insurance company\n",
        "\n",
        "You DO NOT ask the user questions.\n",
        "You DO NOT wait for user input.\n",
        "You COMPLETE the full evaluation in one go.\n",
        "\n",
        "================================\n",
        "PHASE 1: POLICY UNDERSTANDING\n",
        "================================\n",
        "Extract and structure:\n",
        "{ \"coverage_items\": [...], \"exclusions\": [...], \"deductibles\": [...], \"limits\": {...}, \"special_conditions\": [...] }\n",
        "\n",
        "================================\n",
        "PHASE 2: BILL PARSING\n",
        "================================\n",
        "Extract all bill items:\n",
        "[ { \"item\": \"...\", \"cost\": number, \"category\": \"repair/part/labor/service\" } ]\n",
        "\n",
        "================================\n",
        "PHASE 3: CLAIM EVALUATION\n",
        "================================\n",
        "For EACH bill item:\n",
        "- Check if covered under policy\n",
        "- Apply exclusions\n",
        "- Apply limits/deductibles\n",
        "Return:\n",
        "[ { \"item\": \"...\", \"cost\": number, \"covered\": true/false, \"payable_amount\": number, \"reason\": \"short explanation\" } ]\n",
        "\n",
        "================================\n",
        "PHASE 4: FINAL CALCULATION\n",
        "================================\n",
        "- Sum all payable amounts\n",
        "- Apply deductibles if any\n",
        "- Ensure limits are respected\n",
        "\n",
        "================================\n",
        "FINAL OUTPUT (VERY IMPORTANT)\n",
        "================================\n",
        "Return ONLY this JSON:\n",
        "{\n",
        "  \"total_bill_amount\": number,\n",
        "  \"total_covered_amount\": number,\n",
        "  \"total_not_covered_amount\": number,\n",
        "  \"final_payable_by_insurer\": number,\n",
        "  \"breakdown\": [],\n",
        "  \"summary\": { \"covered_items\": [], \"not_covered_items\": [], \"key_reasons\": [] },\n",
        "  \"human_readable_summary\": \"Insurance will pay: ₹XXXXX \\nYou must pay: ₹XXXXX \\nMain uncovered items: ...\"\n",
        "}\n",
        "\n",
        "================================\n",
        "RULES\n",
        "================================\n",
        "- Be precise and simple\n",
        "- No unnecessary text\n",
        "- No explanations outside JSON\n",
        "- No assumptions beyond policy\n",
        "- If unclear, mark as NOT covered with reason\n",
        "- No external APIs\n",
        "- No audio or ElevenLabs\n",
        "\"\"\"\n",
        "\n",
        "    prompt = f\"\"\"\n",
        "INPUT STRUCTURE\n",
        "\n",
        "POLICY:\n",
        "{policy_text}\n",
        "\n",
        "BILL:\n",
        "{bill_text}\n",
        "\"\"\"\n",
        "    \n",
        "    raw_json = call_ollama(prompt, sys_prompt)\n",
        "    try:\n",
        "        data = json.loads(raw_json)\n",
        "        # Extract simple summary securely\n",
        "        simple_msg = data.pop(\"human_readable_summary\", \"No summary returned.\")\n",
        "        return data, simple_msg\n",
        "    except Exception as e:\n",
        "        return {\"error\": \"Failed to parse JSON. Try Again.\", \"raw\": raw_json}, str(e)"
    ],
    [
        "# CELL 4: UI AND AUTOMATED LAUNCHER\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "sample_policy = \"\"\"Car Insurance Policy:\n",
        "\n",
        "- Covers accidental damage to vehicle\n",
        "- Covers collision repairs\n",
        "- Covers parts replacement (except consumables)\n",
        "- Does NOT cover:\n",
        "  - engine damage due to negligence\n",
        "  - normal wear and tear\n",
        "  - tyres and tubes unless damaged in accident\n",
        "\n",
        "Deductible: 2000 INR per claim\n",
        "Maximum coverage per claim: 100000 INR\"\"\"\n",
        "\n",
        "sample_bill = \"\"\"Repair Invoice:\n",
        "\n",
        "1. Front bumper replacement - 15000 INR\n",
        "2. Engine repair - 30000 INR\n",
        "3. Paint work - 8000 INR\n",
        "4. Tyre replacement - 10000 INR\n",
        "5. Labor charges - 7000 INR\"\"\"\n",
        "\n",
        "def gradio_wrapper(policy, bill):\n",
        "    if not policy or not bill:\n",
        "        return {\"error\": \"Provide both text fields.\"}, \"⚠️ Please enter Policy and Bill.\"\n",
        "    return car_claim_evaluator(policy, bill)\n",
        "\n",
        "interface = gr.Interface(\n",
        "    fn=gradio_wrapper,\n",
        "    inputs=[\n",
        "        gr.Textbox(label=\"📑 Car Insurance Policy Rules\", lines=10, value=sample_policy),\n",
        "        gr.Textbox(label=\"🧾 Repair Invoice / Bill Items\", lines=10, value=sample_bill)\n",
        "    ],\n",
        "    outputs=[\n",
        "        gr.JSON(label=\"🖥️ Exact Calculation Breakdown (JSON)\"),\n",
        "        gr.Markdown(label=\"⚡ Simple Human Readable Summary\")\n",
        "    ],\n",
        "    title=\"ClaimGuard AI 🚘 - Car Insurance Claim Evaluator\",\n",
        "    description=\"Instantly evaluate repair bills against insurance policies. No external APIs, exact line-by-line financial breakdown.\"\n",
        ")\n",
        "\n",
        "try:\n",
        "    _ = interface.launch(share=True, inline=False, quiet=True)\n",
        "    print(\"✅ Car Insurance Evaluator Engine Deployed! Use the public *.gradio.live link above.\")\n",
        "except Exception as e:\n",
        "    print(f\"Gradio Launch Error: {e}\")"
    ]
]

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚘 ClaimGuard AI V9 (Car Claim Financial Evaluator)\n",
                "New standalone engine focused on direct financial breakdown, deductibles, and line-item evaluation."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

for i, code_lines in enumerate(cells_content):
    cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": code_lines
    }
    notebook["cells"].append(cell)

with open(r"c:\Users\raj17\Desktop\ClaimGuard AI\ClaimGuard_AI_Kaggle_v9.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("Notebook v9 generated successfully!")
